function FOOTstatistics = FOOTstats(s) 

    FOOTstatistics=table(mean(s)', mad(s)', std(s)', min(s)', max(s)', median(s)', prctile(s,25)', ...
    prctile(s,75)', geomean(abs(s))', harmmean(s)', mode(s)', range(s)', iqr(s)', diag(cov(s)), mad(s)', ...
    std(s,1)', var(s,1)', skewness(s)', kurtosis(s)');
    
    FOOTstatistics.Properties.VariableNames = {'mean_foot', 'mand_foot', 'std_foot', 'min_foot', 'max_foot', 'median_foot', ...
        'prctile25_foot', 'prctile75_foot', 'geomean_foot', 'harmmean_foot', 'mode_foote', 'range_foot', 'iqr_foot', 'diag_foot', ...
        'mad_foot', 'std1_foot', 'var1_foot', 'skew_foot', 'kurtosis_foot'};

   