function HANDstatistics = HANDstats(s) 

    HANDstatistics=table(mean(s)', mad(s)', std(s)', min(s)', max(s)', median(s)', prctile(s,25)', ...
    prctile(s,75)', geomean(abs(s))', harmmean(s)', mode(s)', range(s)', iqr(s)', diag(cov(s)), mad(s)', ...
    std(s,1)', var(s,1)', skewness(s)', kurtosis(s)');
    
    HANDstatistics.Properties.VariableNames = {'mean_hand', 'mand_hand', 'std_hand', 'min_hand', 'max_hand', 'median_hand', ...
        'prctile25_hand', 'prctile75_hand', 'geomean_hand', 'harmmean_hand', 'mode_hande', 'range_hand', 'iqr_hand', 'diag_hand', ...
        'mad_hand', 'std1_hand', 'var1_hand', 'skew_hand', 'kurtosis_hand'};

   